apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-cont-test
spec:
  containers:
  # 1. 메인 컨테이너 (Nginx - 80 포트)
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80

  # 2. 사이드카 컨테이너 (Echo Server - 5678 포트)
    # -listen 옵션으로 포트를 변경하여 80번과 충돌 방지
    # -text 옵션으로 응답 메시지 지정
  - name: echo-sidecar
    image: hashicorp/http-echo
    args:
    - "-text=Hello from Sidecar Container!"
    - "-listen=:5678"
    ports:
    - containerPort: 5678
