apiVersion: v1
kind: Service
metadata:
  labels:
    app: multi-cont-test
  name: multi-cont-pod-nodeport
spec:
  ports:
  - port: 8080
    nodePort: 30080
    protocol: TCP
    targetPort: 80
    name: nginx-port
  - port: 8765
    nodePort: 30765
    protocol: TCP
    targetPort: 5678
    name: echo-port
  selector:
    app: multi-cont-test
  type: NodePort