apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
  labels:
    app: emptydir-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - echo "empty Dir Test" > /home/html/index.html;
      sleep infinity;
    volumeMounts:
    - name: empty-dir
      mountPath : /home/html/
  - name: nginx
    image: nginx
    volumeMounts:
    - name: empty-dir
      mountPath : /usr/share/nginx/html/
    ports:
    - containerPort: 80
  volumes:
  - name: empty-dir
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: emptydir-svc
  labels:
    app: emptydir-pod
spec:
  selector:
    app: emptydir-pod
  type: ClusterIP  
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
