apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  namespace: default
  labels:
    app: hostpath-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    # [핵심 1] 컨테이너 내부의 웹 루트 경로에 마운트
    - name: html-volume
      mountPath: /usr/share/nginx/html
  volumes:
  # [핵심 2] 호스트의 실제 경로를 가리킴
  - name: html-volume
    hostPath:
      path: /data/static-web
      type: Directory  # 해당 경로가 호스트에 반드시 존재해야 함